use serde::{Deserialize, Serialize};

#[allow(dead_code)]
#[derive(Copy, Clone, Debug, Serialize, Deserialize)]
#[repr(u8)]
pub enum Block {
    Air = 0,
    Stone = 1,
    Grass = 2,
    Dirt = 3,
    Cobblestone = 4,
    Wood = 5,
    Sapling = 6,
    Bedrock = 7, // adminium
    Water = 8,
    StillWater = 9,
    Lava = 10,
    StillLava = 11,
    Sand = 12,
    Gravel = 13,
    GoldOre = 14,
    IronOre = 15,
    CoalOre = 16,
    Log = 17,
    Leaves = 18,
    Sponge = 19,
    Glass = 20,
    Red = 21,
    Orange = 22,
    Yellow = 23,
    Lime = 24,
    Green = 25,
    Teal = 26,
    Aqua = 27,
    Cyan = 28,
    Blue = 29,
    Indigo = 30,
    Violet = 31,
    Magenta = 32,
    Pink = 33,
    Black = 34,
    Gray = 35,
    White = 36,
    Dandelion = 37,
    Rose = 38,
    Mushroom = 39,
    RedMushroom = 40,
    Gold = 41,
    Iron = 42,
    DoubleSlab = 43,
    Slab = 44,
    Brick = 45,
    Tnt = 46,
    Bookshelf = 47,
    MossyRocks = 48,
    Obsidian = 49,
}
